# 開発環境向けoverride 用ファイル
services:
  backend:
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # 開発時はこちらを指定
    volumes:
      - ./frontend:/app  # ホストのソースをコンテナにマウント
      - /app/node_modules # node_modulesだけはホスト側と混ざらないように匿名ボリュームで保護
    environment:
      NEXT_PUBLIC_API_URL: ${BACKEND_BASE_URI}
      NEXT_PUBLIC_HOSTNAME: ${SERVER_HOSTNAME}
      INTERNAL_API_URL: ${INTERNAL_BACKEND_API_URL}
      NEXT_PUBLIC_ENV: ${ENV}
      NODE_ENV: ${ENV}
    ports:
      - 3000:3000
