# 開発環境向けoverride 用ファイル
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # 開発時はこちらを指定
    volumes:
      - ./frontend:/app  # ホストのソースをコンテナにマウント
      - /app/node_modules # node_modulesだけはホスト側と混ざらないように匿名ボリュームで保護
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      INTERNAL_API_URL: ${INTERNAL_API_URL}
      NEXT_PUBLIC_DEV_ORG: ${NEXT_PUBLIC_DEV_ORG}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
      NEXT_PUBLIC_ENV: ${ENV}
      NODE_ENV: ${ENV}
    ports:
      - 3000:3000
