user  nginx;
worker_processes  auto;

events {
   worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    # auth_request 用の設定
    include /etc/nginx/auth_request.conf;
    
    upstream backend {
        server backend:8000;
    }

    upstream frontend {
        server frontend:3000;
    }

    upstream roundcube{
        server roundcubemail:80;
    }

    # PhotoPrismのアップストリーム
    upstream photoprism {
        server photoprism:2342;
    }

    server {
        listen 80;
        server_name ${SERVER_HOSTNAME};

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;

        ssl_certificate ${SSL_CERTIFICATE_PATH};
        ssl_certificate_key ${SSL_CERTIFICATE_KEY_PATH};

        location @error401 {
            return 302 /login;
        }

        location @error403 {
            return 403;
        }
        # ============================
        # Frontend
        # ============================
        location / {
            proxy_pass http://frontend;
        }
        location /_next/webpack-hmr {
            proxy_pass http://frontend/_next/webpack-hmr;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        # ============================
        # Backend API
        # ============================
        location /backend/ {
            proxy_pass http://backend;
            # proxy_pass http://backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;        
        }
        # ============================
        # roundcube (SSOのターゲット メールソフト)
        # ============================
        location /mail/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;

            # 末尾の / が重要（パスの付け替え）
            proxy_pass http://roundcube/;
        }
    }
    server {
        listen 2343 ssl;

        ssl_certificate ${SSL_CERTIFICATE_PATH};
        ssl_certificate_key ${SSL_CERTIFICATE_KEY_PATH};

        client_max_body_size 512M;        # Allow large uploads
        proxy_buffering off;              # Stream uploads directly
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;

        location / {
            proxy_pass http://photoprism; 
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            # proxy_set_header Connection "upgrade";
        }
    }
    server {
        listen 9443 ssl;

        ssl_certificate ${SSL_CERTIFICATE_PATH};
        ssl_certificate_key ${SSL_CERTIFICATE_KEY_PATH};

        # ============================
        # roundcube (SSOのターゲット メールソフト)
        # ============================
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;

            # 末尾の / が重要（パスの付け替え）
            proxy_pass http://roundcube/;
        }
    }
}
