user  nginx;
worker_processes  auto;

events {
   worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    # auth_request 用の設定
    include /etc/nginx/auth_request.conf;
    
    # --- アップストリーム定義 ---
    upstream backend {
        server backend:8000;
    }
    upstream frontend {
        server frontend:3000;
    }

    # 個別のサーバー設定は conf.d から読み込む
    include /etc/nginx/conf.d/*.conf;
}
