"""add oidc oidc_refresh_tokens tables

Revision ID: b160328a4196
Revises: 
Create Date: 2026-07-19 01:16:48.442645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b160328a4196'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_authentication_options_session_token'), table_name='authentication_options')
    op.drop_table('authentication_options')
    op.alter_column('credentials', 'credential_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('credentials', 'public_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('credentials', 'sign_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('credentials', 'device_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('credentials', 'user_comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_credentials_user_id'), table_name='credentials')
    op.alter_column('dashboard_links', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='表示名',
               existing_nullable=False)
    op.alter_column('dashboard_links', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='アクセス先URL',
               existing_nullable=False)
    op.alter_column('dashboard_links', 'icon_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='アイコンのパス',
               existing_nullable=True)
    op.alter_column('dashboard_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_access_tokens', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('oidc_access_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_oidc_access_tokens_token'), table_name='oidc_access_tokens')
    op.drop_index(op.f('idx_oidc_access_tokens_user_id'), table_name='oidc_access_tokens')
    op.drop_constraint(op.f('oidc_access_tokens_token_key'), 'oidc_access_tokens', type_='unique')
    op.drop_column('oidc_access_tokens', 'id')
    op.alter_column('oidc_auth_codes', 'redirect_uri',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('oidc_auth_codes', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('oidc_auth_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_oidc_auth_codes_code'), table_name='oidc_auth_codes')
    op.drop_index(op.f('idx_oidc_auth_codes_user_id'), table_name='oidc_auth_codes')
    op.drop_constraint(op.f('oidc_auth_codes_code_key'), 'oidc_auth_codes', type_='unique')
    op.create_index(op.f('ix_oidc_auth_codes_code'), 'oidc_auth_codes', ['code'], unique=True)
    op.create_index(op.f('ix_oidc_auth_codes_id'), 'oidc_auth_codes', ['id'], unique=False)
    op.alter_column('oidc_claim_mappings', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('oidc_claim_mappings', 'claim_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('oidc_claim_mappings', 'value_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('oidc_claim_mappings', 'value_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oidc_claim_mappings', 'static_value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('oidc_claim_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_client_scopes', 'client_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('oidc_client_scopes', 'scope_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('oidc_client_scopes_client_id_scope_name_key'), 'oidc_client_scopes', type_='unique')
    op.alter_column('oidc_clients', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('oidc_clients', 'client_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('oidc_clients', 'client_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.alter_column('oidc_clients', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('oidc_clients', 'allowed_redirect_uris',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False)
    op.alter_column('oidc_clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_scopes', 'scope_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('oidc_scopes', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('oidc_scopes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('one_time_links', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('one_time_links', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('one_time_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_one_time_links_token'), table_name='one_time_links')
    op.drop_index(op.f('idx_one_time_links_user_id'), table_name='one_time_links')
    op.alter_column('registration_sessions', 'session_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('registration_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_registration_sessions_user_id'), table_name='registration_sessions')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='sessions')
    op.alter_column('user_option', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_option', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_option', 'encrypted_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_option', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_option_attributes', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_option_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_option_attributes_key_key'), 'user_option_attributes', type_='unique')
    op.alter_column('users', 'email_verification_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # 初期データの挿入（02_oidc_refsh_add.sql の内容を反映）
    op.execute(
        """
        INSERT INTO oidc_scopes (scope_name, description)
        VALUES ('offline_access', 'リフレッシュトークンの発行を許可（オフラインでのアクセス権限）')
        ON CONFLICT (scope_name) DO NOTHING;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email_verification_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.create_unique_constraint(op.f('user_option_attributes_key_key'), 'user_option_attributes', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_option_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_option_attributes', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_option', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_option', 'encrypted_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_option', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_option', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_registration_sessions_user_id'), 'registration_sessions', ['user_id'], unique=False)
    op.alter_column('registration_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('registration_sessions', 'session_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_one_time_links_user_id'), 'one_time_links', ['user_id'], unique=False)
    op.create_index(op.f('idx_one_time_links_token'), 'one_time_links', ['token'], unique=False)
    op.alter_column('one_time_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('one_time_links', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('one_time_links', 'token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_scopes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_scopes', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oidc_scopes', 'scope_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_clients', 'allowed_redirect_uris',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('oidc_clients', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oidc_clients', 'client_secret',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_clients', 'client_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_clients', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('oidc_client_scopes_client_id_scope_name_key'), 'oidc_client_scopes', ['client_id', 'scope_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('oidc_client_scopes', 'scope_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_client_scopes', 'client_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_claim_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_claim_mappings', 'static_value',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oidc_claim_mappings', 'value_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oidc_claim_mappings', 'value_source',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_claim_mappings', 'claim_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_claim_mappings', 'scope',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_oidc_auth_codes_id'), table_name='oidc_auth_codes')
    op.drop_index(op.f('ix_oidc_auth_codes_code'), table_name='oidc_auth_codes')
    op.create_unique_constraint(op.f('oidc_auth_codes_code_key'), 'oidc_auth_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_oidc_auth_codes_user_id'), 'oidc_auth_codes', ['user_id'], unique=False)
    op.create_index(op.f('idx_oidc_auth_codes_code'), 'oidc_auth_codes', ['code'], unique=False)
    op.alter_column('oidc_auth_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_auth_codes', 'scope',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oidc_auth_codes', 'redirect_uri',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('oidc_access_tokens', sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('oidc_access_tokens_token_key'), 'oidc_access_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_oidc_access_tokens_user_id'), 'oidc_access_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_oidc_access_tokens_token'), 'oidc_access_tokens', ['token'], unique=False)
    op.alter_column('oidc_access_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oidc_access_tokens', 'token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('dashboard_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dashboard_links', 'icon_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='アイコンのパス',
               existing_nullable=True)
    op.alter_column('dashboard_links', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='アクセス先URL',
               existing_nullable=False)
    op.alter_column('dashboard_links', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='表示名',
               existing_nullable=False)
    op.create_index(op.f('idx_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.alter_column('credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credentials', 'user_comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('credentials', 'device_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('credentials', 'sign_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('credentials', 'public_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('credentials', 'credential_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('authentication_options',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('session_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('challenge', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('authentication_options_pkey'))
    )
    op.create_index(op.f('idx_authentication_options_session_token'), 'authentication_options', ['session_token'], unique=False)
    # ### end Alembic commands ###
